### ISSUE TITLE
Missing modules files in v5 on NPM

### ISSUE THREAD

**Issue by peterblazejewicz** [jonathantneal/postcss-focus-within#10]
Issue: it seems content published to NPM is missing modules files, so any new instlalation fails and complaints about module resolution failing:

```bash
npm notice package: postcss-focus-within@5.0.0
npm notice === Tarball Contents ===
npm notice 2.0kB package.json
npm notice 6.8kB LICENSE.md
npm notice 3.9kB README.md
````

Thanks!

**Comment by jonathantneal** [comment]
This should be resolved in 5.0.1. 🙏 I’m sorry for the delay!
